import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/app/components/Navbar";
import BootstrapClient from "./components/BoostrapClient";
import AuthProvider from "./auth/Provider";

const virgil = localFont({
  src: "../public/fonts/virgil.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={virgil.className}>
        <AuthProvider>
          <Navbar />
          {children}
          <BootstrapClient />
        </AuthProvider>
      </body>
    </html>
  );
}
